"""
Task model definitions for API contracts.

Connects to:
  - orchestrator.weaver.run_task() for planning
  - orchestrator.persistence for Neo4j task nodes
  - orchestrator.constitution for safety violations
  - orchestrator.sandbox for execution results
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum


class TaskStatus(str, Enum):
    """Task execution status enumeration."""
    PENDING = "pending"
    PLANNING = "planning"
    CONSTITUTION_CHECK = "constitution_check"
    AWAITING_APPROVAL = "awaiting_approval"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    BLOCKED = "blocked"


class SafetyTag(str, Enum):
    """Safety tags assigned by Weaver during planning."""
    API_REQUIRED = "API_REQUIRED"
    FILESYSTEM_MODIFY = "FILESYSTEM_MODIFY"
    NETWORK_REQUIRED = "NETWORK_REQUIRED"
    SENSITIVE_DATA = "SENSITIVE_DATA"
    DANGEROUS_COMMAND = "DANGEROUS_COMMAND"


class TaskRequest(BaseModel):
    """User-submitted task request.
    
    Maps to orchestrator.weaver.run_task(request: str)
    """
    description: str = Field(..., description="Natural language task description")
    tenant_id: str = Field(..., description="Tenant ID for multi-tenant isolation")
    require_approval: bool = Field(default=False, description="Force human approval before execution")
    timeout_seconds: int = Field(default=300, description="Max execution time")
    
    class Config:
        json_schema_extra = {
            "example": {
                "description": "Analyze CSV data and post summary to Slack",
                "tenant_id": "tenant_123",
                "require_approval": True,
                "timeout_seconds": 600
            }
        }


class PlanResponse(BaseModel):
    """Execution plan generated by Weaver.
    
    Maps to orchestrator.weaver.run_task() output schema.
    """
    task_id: str = Field(..., description="Unique task ID (UUID)")
    intent: str = Field(..., description="High-level summary of what the plan accomplishes")
    safety_tags: List[SafetyTag] = Field(default_factory=list, description="Safety tags from Weaver")
    steps: List[Dict[str, Any]] = Field(..., description="Execution steps with code")
    violations: List[Dict[str, Any]] = Field(default_factory=list, description="Constitution violations (if any)")
    requires_approval: bool = Field(..., description="True if Navigator approval needed")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_schema_extra = {
            "example": {
                "task_id": "task_abc123",
                "intent": "Read CSV, compute stats, post to Slack",
                "safety_tags": ["API_REQUIRED", "FILESYSTEM_MODIFY"],
                "steps": [
                    {"step": 1, "description": "Read data.csv", "code": "import pandas as pd\ndf = pd.read_csv('data.csv')"}
                ],
                "violations": [],
                "requires_approval": True,
                "created_at": "2026-05-31T12:00:00Z"
            }
        }


class ExecutionResponse(BaseModel):
    """Result from sandbox execution.
    
    Maps to orchestrator.sandbox execution output.
    """
    task_id: str = Field(..., description="Task ID")
    status: TaskStatus = Field(..., description="Final status after execution")
    output: Optional[str] = Field(default=None, description="Stdout from execution")
    error: Optional[str] = Field(default=None, description="Error message or stderr")
    duration_ms: int = Field(..., description="Execution time in milliseconds")
    neo4j_nodes_created: int = Field(default=0, description="Audit nodes written to Neo4j")
    completed_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_schema_extra = {
            "example": {
                "task_id": "task_abc123",
                "status": "completed",
                "output": "Processed 1000 rows, mean=42.5, variance=12.3. Posted to #analytics.",
                "error": None,
                "duration_ms": 2340,
                "neo4j_nodes_created": 7,
                "completed_at": "2026-05-31T12:05:00Z"
            }
        }


class TaskResponse(BaseModel):
    """Combined task response (plan + execution).
    
    Returned to client via REST or WebSocket.
    """
    task_request: TaskRequest
    plan: Optional[PlanResponse] = None
    execution: Optional[ExecutionResponse] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "task_request": {
                    "description": "Analyze CSV data and post summary to Slack",
                    "tenant_id": "tenant_123",
                    "require_approval": True,
                    "timeout_seconds": 600
                },
                "plan": {
                    "task_id": "task_abc123",
                    "intent": "Read CSV, compute stats, post to Slack",
                    "safety_tags": ["API_REQUIRED"],
                    "steps": [],
                    "violations": [],
                    "requires_approval": True,
                    "created_at": "2026-05-31T12:00:00Z"
                },
                "execution": {
                    "task_id": "task_abc123",
                    "status": "completed",
                    "output": "Done",
                    "error": None,
                    "duration_ms": 2340,
                    "neo4j_nodes_created": 7,
                    "completed_at": "2026-05-31T12:05:00Z"
                }
            }
        }
